### ISSUE TITLE
Tremor Raw ProgressBar code is showing ProgressCircle code

### ISSUE THREAD

**Issue by Spherrrical** [tremorlabs/tremor#18]
### Tremor Raw Component Version

Newest Available

### Link to minimal reproduction

https://raw.tremor.so/docs/visualizations/progress-bar

### Steps to reproduce

Go to the link, and click on the code for ProgressBar.

### What is expected?

Should show ProgressBar code, with exportable member ProgressBar.

### What is actually happening?

Showing ProgressCircle code.

### What browsers are you seeing the problem on?

Safari, Other

**Comment by severinlandolt** [comment]
Thank you for the hint! Should be fixed now.
