### ISSUE TITLE
[Bug]: Tooltip component must needs `"use client";`

### ISSUE THREAD

**Issue by 134130** [tremorlabs/tremor#30]
### Link to minimal reproduction

https://raw.tremor.so/docs/ui/tooltip

### Steps to reproduce

1. Initialize your project with installation guideline.
2. Follow tooltip component guide line.

### What is expected?

no error

### What is actually happening?

build failing.

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Thanks @134130, just fixed it!
