### ISSUE TITLE
[Bug]: TabsNavigation components doens't match his examples

### ISSUE THREAD

**Issue by grsantos2215** [tremorlabs/tremor#31]
### Tremor Raw Component Version

0.0.0

### Link to minimal reproduction

https://raw.tremor.so/docs/ui/tab-navigation

### Steps to reproduce

Just copy and paste the code on the project and try to import him.

### What is expected?

the component is expected to work as in the example

### What is actually happening?

On the examples, its possible to see this code:
![image](https://github.com/tremorlabs/tremor-raw/assets/45048902/b8bd92e9-bbbf-4b48-88a5-d5d6c0675bba)

But, when copy and paste the component for the project, the code is that:
![image](https://github.com/tremorlabs/tremor-raw/assets/45048902/c0b04bdf-78d3-4008-857e-1aa1b0e063ca)

And the href prop don't exist on the code.

### What browsers are you seeing the problem on?

Chrome, Other

**Comment by severinlandolt** [comment]
On it!

**Comment by grsantos2215** [comment]
Hi @severinlandolt, thanks for the update, but I really copy the correct component, you can see on the "add component" section the same imports of my code

https://raw.tremor.so/docs/ui/tab-navigation

**Comment by severinlandolt** [comment]
Ah, I misunderstood your intention, my bad! Should be fixed by now :)

**Comment by grsantos2215** [comment]
Really Thanks.
