### ISSUE TITLE
[Feature]: Add Carousel Component

### ISSUE THREAD

**Issue by askadityapandey** [tremorlabs/tremor#35]
### What problem does this feature solve?

I have been exploring the library and found it incredibly useful for building modern UIs with ready-made React components. However, I noticed that a carousel component is currently missing from the library, which I believe could be a valuable addition.
I would like to propose the addition of a carousel component to the library. This component could include the following features:

- Display multiple items/images in a sliding manner.
- Navigation controls (next/prev buttons).
- Auto-scroll functionality with configurable interval.
- Customizable transition effects.
- Responsive design to adapt to various screen sizes.

I am willing to contribute to this feature by developing the carousel component. Before proceeding, I wanted to get feedback from the maintainers and ensure that this aligns with the project's goals and standards.

**Comment by severinlandolt** [comment]
Hi @askadityapandey, thanks for taking your time and creating this feature request. We had a look at it and concluded, that there isn't much value added by providing such a component. There are very nice examples of this component here: https://www.embla-carousel.com/examples/predefined/

Adding a Tremor abstraction on top does not feel right here. 

Thanks!
