### ISSUE TITLE
[Feature]: Input password field should have option to not allow to text transformation

### ISSUE THREAD

**Issue by Muchaszewski** [tremorlabs/tremor#42]
### What problem does this feature solve?

When using the "password" type on Input, there is always a button to show a password as plain text. I have a business requirement that it should only allow that for one password field, but not for repeat-password for security reasons.

Although easy to fix with raw library i would love to see this as core

### What does the proposed API look like?

//small pseudocode snipet on how to improve the Input field
```
{(isPassword && allowPasswordVisibility) && (
          <div
            className={cx(
              "absolute bottom-0 right-0 flex h-full items-center justify-center px-3",
            )}
          >
            <button
              aria-label="Change password visibility"
```

**Comment by severinlandolt** [comment]
Hi @Muchaszewski, thanks for your proposal! Interesting proposal, have not thought about this. As you mentioned, this feature is quickly implemented, thus we won't add this to the raw component. But will probably add a new block with this in mind👍
