### ISSUE TITLE
[Bug]: Bar Chart code is actually Line Chart's

### ISSUE THREAD

**Issue by qu8n** [tremorlabs/tremor#49]
### Tremor Raw Component Version

0.2.2

### Link to minimal reproduction

N/A

### Steps to reproduce

See the [Bar Chart](https://raw.tremor.so/docs/visualizations/bar-chart) page.
![CleanShot 190320](https://github.com/tremorlabs/tremor-raw/assets/86090707/013aa23b-a5fd-49cd-b17f-fd464e2be6dd)

### What is expected?

The code on the [Bar Chart](https://raw.tremor.so/docs/visualizations/bar-chart) page shows **Line Chart** code.

### What is actually happening?

The code on the [Bar Chart](https://raw.tremor.so/docs/visualizations/bar-chart) page shows **Bar Chart** code.

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Loving your work! Thank you Tremor team.

**Comment by severinlandolt** [comment]
Oh, fixed!
