### ISSUE TITLE
[Bug]: The chartColors class name in chartUtils.ts is not compiled into the final css file

### ISSUE THREAD

**Issue by myesn** [tremorlabs/tremor#89]
### Tremor Raw Component Version

v0.1.0

### Link to minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-jxuzeb?file=app%2Fpage.tsx

### Steps to reproduce

.

### What is expected?

set color

### What is actually happening?

cannot set color

**Comment by severinlandolt** [comment]
Hi @myesn!

Have you made sure to include the utils file/folder in the tailwind config?
![CleanShot 2024-09-15 at 17 03 19@2x](https://github.com/user-attachments/assets/55defc32-d177-47ae-b3c7-bf8730d99ecf)

**Comment by severinlandolt** [comment]
Hi @myesn, I see you are not using the `src` folder. This messes up the content imports in the `tailwind.config`.

You should update the content paths to match your app structure. In your case, remove the source part in the paths.
<img width="517" alt="image" src="https://github.com/user-attachments/assets/8b412cba-08f7-412b-942e-87cb09981d89">

**Comment by myesn** [comment]
Thank you very much for your reply, it has been resolved.
