### ISSUE TITLE
[Feature]: Organizing Items in Table Component by Next.js using @tremor/react

### ISSUE THREAD

**Issue by DhanielB** [tremorlabs/tremor#983]
### What problem does this feature solve?

**Overview**
The current implementation of the table component provided by @tremor/react lacks the functionality to organize items by order, and drag-drop function. This functionality is crucial for users who need to sort the displayed data efficiently. In this issue, we aim to enhance the table component to support sorting functionality.

**Proposed Solution**
Sorting Functionality: Implement sorting functionality for the table component. Users should be able to click on column headers to sort the table data based on that column in ascending or descending order.

User Interaction: Provide visual feedback to users indicating the current sorting order (ascending/descending) when a column header is clicked.

Flexibility: Ensure that the sorting functionality is flexible and can handle various data types (e.g., strings, numbers, dates) appropriately.

Additional Notes
Collaborate with the development team at @tremor/react to ensure alignment with their roadmap and coding standards.
Consider potential edge cases and handle them gracefully to provide a seamless user experience.
By addressing this issue, we can enhance the usability and effectiveness of the table component in Next.js applications utilizing @tremor/react.

### What does the proposed API look like?

References:
**https://youtu.be/QvuQ3888xyE?si=8VDH37zWRJJhqg2D** *
**https://www.youtube.com/watch?v=ran0d8WHTYs** *

https://www.smashingmagazine.com/2020/03/sortable-tables-react/

**_### Bold text (*) is mandatory to understand the features_**

**Comment by severinlandolt** [comment]
Hi! We want to keep out table as leightweight as possible, hence, we won't be adding this to our base table. 

If you are interested in more sophisticated table functionalities, we cover them in our Blocks:
* [Table Actions (e.g. sorting)](https://blocks.tremor.so/blocks/table-actions)
* [Table Pagination](https://blocks.tremor.so/blocks/table-pagination)

**Comment by DhanielB** [comment]
Oh, ok. Thanks!
